#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/init.h>

#include "kernel_helper.h"

/*
 * This is a test to show how you can find out your own modules name
 *
 * This shows that you can access the module name in two ways:
 * - through a macro of the compiler called KBUILD_MODNAME.
 * - through access to the private data section of this module (THIS_MODULE).
 *   	from this private data section you can access other info about the module
 *   	(which is shown later).
 *   	Actually, if you look at the source of the autogenerated c file for your module
 *   	usually called youmodule.mod.c you can see this structure and the fact
 *   	that THIS_MODULE->name is defined as KBUILD_MODNAME.
 */

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Mark Veltzer");
MODULE_DESCRIPTION("Demo module for testing");

// parameters for this module

// constants for this module

// our own functions
static int __init mod_init(void) {
	INFO("start");
	INFO("name is %s", KBUILD_MODNAME);
	INFO("name is %s", THIS_MODULE->name);
	INFO("srcversion is %s", THIS_MODULE->srcversion);
	INFO("vermagic is %s", THIS_MODULE->vermagic);
	return(0);
}


static void __exit mod_exit(void) {
	INFO("start");
}


// declaration of init/cleanup functions of this module

module_init(mod_init);
module_exit(mod_exit);
