#include<stdio.h>

/*
 * This example shows the page faults that are generated by access to an mmaped file.
 *
 * The example maps the full /etc/passwd file to user space.
 *
 * 	Mark Veltzer
 */

int main(int argc,char** argv,char** envp) {
	printf("stdout data");
	fprintf(stderr,"stderr data");
	printf("stdout data2");
	fprintf(stderr,"stderr data2");
	printf("\n");
	printf("help me user!!!!");
	*(char*)0=0;
}
