/*
        This file is part of the linuxapi project.
        Copyright (C) 2011-2013 Mark Veltzer <mark.veltzer@gmail.com>

        The linuxapi package is free software; you can redistribute it and/or
        modify it under the terms of the GNU Lesser General Public
        License as published by the Free Software Foundation; either
        version 2.1 of the License, or (at your option) any later version.

        The linuxapi package is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        Lesser General Public License for more details.

        You should have received a copy of the GNU Lesser General Public
        License along with the GNU C Library; if not, write to the Free
        Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
        02111-1307 USA.
 */

#include <firstinclude.h>
#include <stdlib.h>	// for EXIT_SUCCESS

/*
 * This is a simple example causing a core dump.
 *
 * The address "0" is not mapped into a processes virtual address space which is a good
 * thing since NULL is actually 0.
 *
 * Debug this program by running it:
 **=================================
 * $> ./src/examples/debugging/cause_core_dump.exe
 * Segmentation fault (core dumped)
 * $> gdb ./src/examples/debugging/cause_core_dump.exe
 * GNU gdb (GDB) 7.5-ubuntu
 * Copyright (C) 2012 Free Software Foundation, Inc.
 * License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 * This is free software: you are free to change and redistribute it.
 * There is NO WARRANTY, to the extent permitted by law. Type "show copying"
 * and "show warranty" for details.
 * This GDB was configured as "i686-linux-gnu".
 * For bug reporting instructions, please see:
 * <http://www.gnu.org/software/gdb/bugs/>...
 * Reading symbols from /home/mark/git/remote_branches/linuxapi/src/examples/debugging/cause_core_dump.exe...done.
 * (gdb) core core
 * warning: core file may not match specified executable file.
 * [New LWP 12005]
 * warning: Can't read pathname for load map: Input/output error.
 * Core was generated by `./src/examples/debugging/cause_core_dump.exe'.
 * Program terminated with signal 11, Segmentation fault.
 * #0 main (argc=1, argv=0xbf966ca4, envp=0xbf966cac) at src/examples/debugging/cause_core_dump.cc:50
 * 50 *(char *)0=0;
 * (gdb)
 *
 * EXTRA_COMPILE_FLAGS=-g3
 */

int main(int argc, char** argv, char** envp) {
	*(char *)0=0;
	return EXIT_SUCCESS;
}
