name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-22.04"
            python-version: "3.11"
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: bootstrap-pip
      run: python -m pip install --upgrade pip
    - name: bootstrap
      run: python -m pip install pydmt
    - name: pydmt
      run: pydmt build
